name: .NET Core

on:
  push:
    branches: [ master, development ]
  pull_request:
    branches: [ master, development ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: App Settings substituting variables
      uses: microsoft/variable-substitution@v1 
      with:
        files: 'Anoroc-User-Management/appsettings.json' 
      env: 
        SQL_Connection_String: ${{ secrets.SQL_Connection_String }}
        
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    
    - name: Install dependencies
      run: dotnet restore
    
    - name: Building project
      run: dotnet build --configuration Release --no-restore
      
    - name: Key.json substituting variables
      uses: microsoft/variable-substitution@v1
      with:
        files: '${{env.DOTNET_ROOT}}/myapp/key.json'
      env:
        private_key_id: ${{ secrets.private_key_id }}
        private_key: ${{ secrets.private_key }}
        client_email: ${{ secrets.client_email }}
        client_id: ${{ secrets.client_id }}
    
    - name: Unit and Integration tests
      run: dotnet test --no-restore
